### ISSUE TITLE
about precomputed kernel

### ISSUE THREAD

**Issue by sassan72** [google/neural-tangents#115]
Is it possible to do classification based on precomputed kernel?

**Comment by sassan72** [comment]
i have done quantum version of neural network algorithm for classification. I can calculate a parameterized quantum kernel matrix with quantum gate operation. I wanted to know how i can use neural-tangent

**Comment by romanngg** [comment]
Just in case for future references, I believe the answer is yes,
* [`nt.predict.gp_inference`](https://neural-tangents.readthedocs.io/en/latest/neural_tangents.predict.html#neural_tangents.predict.gp_inference),
* [`nt.predict.gradient_descent`](https://neural-tangents.readthedocs.io/en/latest/neural_tangents.predict.html#neural_tangents.predict.gradient_descent),
* [`nt.predict.gradient_descent_mse`](https://neural-tangents.readthedocs.io/en/latest/neural_tangents.predict.html#neural_tangents.predict.gradient_descent_mse)

all work with pre-computed kernels `k_train_train`. Hope this answers the question!
