### ISSUE TITLE
Questions about concat and logic of specifying number of neurons

### ISSUE THREAD

**Issue by kayhan-batmanghelich** [google/neural-tangents#16]
Hi,

Thank you for sharing this great library. I have two questions which are relevant to each other:

1. For `nngp`, we are assuming that the number of neurons goes to infinity. Why do you need to specify the number of neurons in the `Dense` (or the number of filters in `conv`) layer? Is this because we are not sure if the layer is mid or last layer?

2. The answer to the first questions somewhat answers to this question: Does it make sense to have `FanInConcat` layer (the same as `stax`)? From one point of view, it doesn't b/c we are concatenating two infinities many layers. From another point of view, it does. For example, if you want to implement models like UNet, you need ` FanInConcat` and I personally think it makes sense to implement it but I not sure.

I would be thankful if you clarify.

Thanks

**Comment by romanngg** [comment]
Hi Kayhan,

1) For the analytic kernel evaluation (using `stax.py`), the number of neurons is not used, even for the last layer. The kernel is implicitly assumed to be block-identical along the last layer feature/channel dimension, and during inference the number of neurons is inferred from the training / test data (e.g. `y_train.shape == (50000, 10)` for CIFAR-10 classifier outputs).

The number of neurons is used, however, whenever a final network is involved, e.g. when using the `apply_fn`, `init_fn` returned by code blocks like this:
```
init_fn, apply_fn, kernel_fn = stax.serial(
    stax.Dense(512), stax.Relu(),
    stax.Dense(512), stax.Relu(),
    stax.Dense(1)
)
```
So this specific width will be considered if you decide to either train this network as usual or decide to construct the empirical kernel by calling `nt.monte_carlo_kernel_fn(init_fn, apply_fn, key, n_samples)`, or `nt.empirical_kernel_fn(apply_fn)` etc.

So if you don't need empirical kernels or finite networks feel free to disregard these parameters (they do not impact `kernel_fn`, apart from some metadata properties like `kernel.shape1` and `kernel.shape2` of the resulting kernel). If you want to compare your infinite models to finite ones via training or empirical kernels, this could be a convenient way to do it though!


2) I think it totally makes sense, and hopefully we'll have something for that soon (https://github.com/google/neural-tangents/projects/1#card-30853879). There might be some challenging conditions/edge cases, but for some settings it should be feasible! Will update on this later.

**Comment by kayhan-batmanghelich** [comment]
Hi @romanngg ,

Thanks for the clear answer. I was trying to implement UNet to learn this library and the UNet needs `FanInConcat` and `upsample`. For now, I have implemented `ConvTranspose` instead of `upsample` and I thought, just to make it run, I can replace `FanInConcat` with `FanInSum`.

If you don't mind, I can pull request the `convTranspose`.

**Comment by romanngg** [comment]
Definitely, please do!

**Comment by kayhan-batmanghelich** [comment]
@romanngg  I just pull requested the `convTrans`. It contains my initial effort for `FanInConcat` as well but it seems `FanInConcat` is more complicated.
