### ISSUE TITLE
neural tangents vs flax

### ISSUE THREAD

**Issue by po-oya** [google/neural-tangents#162]
Hi

I am new to JAX, and my question is can we use this package to train regular neural networks without the NTK notion? If this is the case, are there any examples or a document to start with?

Thanks!

**Comment by Sohl-Dickstein** [comment]
Note that if *all* you want to do is train finite-width neural networks,
and you are not interested in computing the network's NTK or NNGP kernel or
a linearization of the network, then FLAX would be a better choice.

**Comment by po-oya** [comment]
Thanks for your help!
