### ISSUE TITLE
Are the parameters of the elementwise nonlinear layers trainable?

### ISSUE THREAD

**Issue by rishiedupalli** [google/neural-tangents#174]
Is it possible to train the parameters (e.g gamma in the RBF kernel) of the elementwise nonlinear kernels? Thank you for your time!

**Comment by romanngg** [comment]
Yes, all parameters are generally differentiable. I'm on my phone but something like

```
def kernel_fn(gamma, X1, X2):
    _, _, k_fn = nt.stax.Rbf(gamma)
    return k_fn(X1, X2)


jax.grad(kernel_fn)(gamma, X1, X2)
# or jax.jacobian
```
Should work. Can write a more detailed example later!

**Comment by rishiedupalli** [comment]
I would greatly appreciate that if possible! Is it also possible to access the trained gamma parameter after performing inference in nngp mode?

**Comment by romanngg** [comment]
Yes, in general you can differentiate and access any differentiable parameters that you want. Here's a full example:
https://colab.research.google.com/gist/romanngg/b888b271ad5f14cf0d0d0a6851a3d5fc/nt_gamma_tuning.ipynb

Lmk if this helps!

**Comment by rishiedupalli** [comment]
Thank you so much! This clears everything up!
