### ISSUE TITLE
using stax.Cos(a=1.0, b=1.0, c=0.0) to get kernel from conv layer gives error

### ISSUE THREAD

**Issue by ShenLi00011** [google/neural-tangents#192]
Hi,
I am trying to generate conv kernel using the infinite network example given in the documentation . 
 https://neural-tangents.readthedocs.io/en/latest/stax.html

I am trying to add a activation stax.Cos(a=1.0, b=1.0, c=0.0) but it gives error:

ValueError: The input to the activation function must be Gaussian, i.e. a random affine transform is required before the activation function.

I do not understand how to add random affine transform. What to do?
Thank you

**Comment by romanngg** [comment]
Do you have a code snippet? Usually this error arises if you stack two nonlinearities one after another (e.g. Cos after ReLU), in which case the exact analytic infinite width limit is not known; but when inputs to nonlinearities are iid Gaussians (i.e. after Conv, Dense, ConvLocal, ConvTranspose etc layers with iid random weights), then the limiting covariance matrix of nonlinearity outputs can be computed.

**Comment by ShenLi00011** [comment]
yes i was using the same code in the example without the flatten layer, and yes there was two non linearties one after another, after removing one it worked, but the dim of the cntk(because it uses the conv layer?) becomes 6D. how i can reduce it to 3 or 4 dimensions. Thank you .

**Comment by romanngg** [comment]
If there's no flatten layer, the covariance of activations, which have shapes `(n1, h, w, c)` and `(n2, h, w, c)`, will tend to a dense 6D matrix of shape `(n1, n2, h, h, w, w)`, as `c` is taken to infinity. This is why the covariance is 6D. When a flattened layer is used, the network output covariance has shape `(n1, n2)` (2D), and to compute it, only the diagonal entries of intermediary layer covariances are needed, hence it only computes a 4D `(n1, n2, h, w)` matrix in intermediary layers (and not full 6D covariances).

> how i can reduce it to 3 or 4 dimensions

You can extract the diagonal(s) form the 6D matrix, or have your network terminate with a flattening layer. It depends on why exactly you want the shapes to be 3 or 4D.

**Comment by ShenLi00011** [comment]
hi, i am student, i saw for matrix decomposition, when i ask in google bard it says, "unavailable element can be written as a linear combination of available elements. and the coefficient of this combination can be found in a 4d array. for example if the value at (2,3,1,4) is 0.5 then it means the available element at (1,4) contributes 0.5 to the unavailable element at (2,3)" . so the 4d array. so just taking the diagonal entries from the 6d array will work?

**Comment by ShenLi00011** [comment]
i am a student, sorry for mistakenly deleting the comment. in between as you said extracting the diagonals gives me a 2d, 3d and 4d. thank you for replies. and this conv ntk is it the cntk? thank you

**Comment by ShenLi00011** [comment]
Hi, i have used ConvLocal() which made the kernel 6d to d, i amm confused now is  is from (n1, n2, h, h, w, w) to (n1, n2, h, h,) or (n1, n2, w, w) or ( h, h, w, w), did not find a reference for this is the docs. what will it be...? thank you

**Comment by ShenLi00011** [comment]
I hope you will have time to reply. I have used dense layer model example given in the documentation, by using data N=32, (32,32), this gives me a ntk, but according to the definition it should be positive definite and symmetric. Why it is not?
