### ISSUE TITLE
Custom layers adding in stax.serial

### ISSUE THREAD

**Issue by jaya-pret** [google/neural-tangents#195]
HI, Thank you for the nice work. I am trying to do kernel ridge regression with ntk. to do that i need down and upsampling layers. the following code i am using. 

https://gist.github.com/jaya-pret/7eeb6a7edb26d4e3ea54f027ad1a2d2a

now for a given input x1 = (n1, h, w, c) how i can add upsampling and downsampling in this . and the ntk is not positive definite, the initailisation is random.uniform for x1. i have also tried jnp.ones with low value but then the kernel value becomes all same! is there any layers i can add so that the kernel value changes for ntk  and becomes positive definite, or it depends on the data type. thank you.

**Comment by romanngg** [comment]
1) Re up/downsampling, we have the `ImageResize` layer https://neural-tangents.readthedocs.io/en/latest/_autosummary/neural_tangents.stax.ImageResize.html#neural_tangents.stax.ImageResize - would it work for you?

2) It's a bit hard to diagnose non-PSDness, I may need to see the full code. Note that `A` won't be PSD unless `x1 == x2`, and if `x1 == x2`, you may want to try computing it as `A = kernel_fn(x1, None, 'ntk')`, which can be a bit more numerically stable.

Lmk if this help!

**Comment by jaya-pret** [comment]
hi. Yes the link helps a lot, Thank you so much for your fast reply. I will update the full code with x1=x2 and share, so you can see the implementation. 

Many thanks for your answers!

**Comment by jaya-pret** [comment]
Hi , i have used the image.resize layer, it took some time for me to understand. the code is here:

https://gist.github.com/jaya-pret/82bc2363c0a5906a1af8a7727641dad5

I have doubt if it is the correct way of doing it. 

Thank you.

**Comment by jaya-pret** [comment]
HI, i want to wish you first merry Xmas and happy new year. here is the code i am trying to write with your suggested layer:
https://gist.github.com/jaya-pret/9cb8deac7af264809a2ffa30c4f57a76
i have doubt if it is right way of doing it.
Wish you again all the best and a great time , thank you
