### ISSUE TITLE
Can A transpose conv function be added later?

### ISSUE THREAD

**Issue by shinel94** [google/neural-tangents#22]
Hi! Thanks for this awesome API. I try to apply this API to segmentation task so i was wondering if the code supports (or could support with simple extensions) transpose convolution layers(deconvolution layer). If not, is the obstacle practical or theoretical?
--

**Comment by romanngg** [comment]
The obstacle was mostly practical: some previously missing / broken features in JAX, like https://github.com/google/jax/issues/3972, https://github.com/google/jax/issues/3973, https://github.com/google/jax/issues/3793, and also even in finite-width there was no known to me implementation of transpose circular convolution (which is one of the padding modes that we support) in any other libraries, so we had to implement that logic as well. But it's finally here! https://github.com/google/neural-tangents/commit/780ad0ce22d482bcefd12f4d3390090de7206da5
