### ISSUE TITLE
MaxPool for NT

### ISSUE THREAD

**Issue by jiachangliu** [google/neural-tangents#27]
Hello, I notice there is no maxpooling in the stax library. Is there any way for me to put such maxpooling layer in my stax.serial() and compute the posterior for nngp or ntk?

I read the paper on arXiv NEURAL TANGENTS: FAST AND EASY INFINITE NEURAL NETWORKS IN PYTHON. The paper suggests to use Monte Carlo sampling technique to approximate the network distribution. My question is how do I construct the network in the first place since there is no maxpooling in the stax library? Currently, there are only avgPool and sumPool. Thanks!

**Comment by SiuMath** [comment]
You can use the original *stax* to define your function and use
nt.emprical_kernel_fn
to compute the empirical NNGP/NTK.
For example,
*import neural_tangents as nt*
*from jax.experimental import stax as ostax  *
*kernel_fn = nt.emprical_kernel_fn(f) *
where *f* is a function defined using ostax, which contains MaxPool and
others (https://github.com/google/jax/blob/master/jax/experimental/stax.py).

To get Monte Carlo sampling, just apply *monte_carlo_kernel_fn *in
https://github.com/google/neural-tangents/blob/master/neural_tangents/utils/monte_carlo.py

**Comment by jiachangliu** [comment]
Wow thank you! I'll try it.
