### ISSUE TITLE
Using internal packages 

### ISSUE THREAD

**Issue by ravidziv** [google/neural-tangents#3]
Hi,
you are using internal packages in your code.  For example,  in the neural_tangents_cookbook.ipynb
"from google3.pyglib import gfile
with gfile.GFile( '/cns/od-d/home/schsam/rs=6.3/ntk/gd_inference.pdf', 'w') as f_out:"

**Comment by sschoenholz** [comment]
Thanks for pointing this out! It was left over from a mad dash of paper writing. We pushed a fix, but please let us know if you find anything else.
