### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by tancik** [google/neural-tangents#33]
I believe the following line should be `kernel_fn(x_test, x_train, params)` instead of `kernel_fn(x_train, x_test, params)`.

https://github.com/google/neural-tangents/blob/38e9ba906f9cac7a6daa270c28b9d0c16f5335be/neural_tangents/predict.py#L79

**Comment by romanngg** [comment]
Thanks for spotting this and sorry for the huge delay - fixed in a76bbb494f19af4f8c9c1a1b0904e91b105f769e!
