### ISSUE TITLE
Bug still exists when installing neural-tangents from `pip3`

### ISSUE THREAD

**Issue by DarrenZhang01** [google/neural-tangents#37]
When installing using `pip3` on my PC, the bug in line 421 of `neural_tangents/utils/batch.py` still exists (i.e., `np.onp`), although it seems to have already been revised in commit [https://github.com/google/neural-tangents/commit/272dc5e7717ecc920ff371572dfe3ab3f4e68bd4](https://github.com/google/neural-tangents/commit/272dc5e7717ecc920ff371572dfe3ab3f4e68bd4)

![bug](https://user-images.githubusercontent.com/29133834/82956885-ca2f9380-9f7f-11ea-8475-1e57a6f0b008.png)

**Comment by romanngg** [comment]
Thanks for noticing this! Just pushed current code to pypi, so this should be fixed from NT version >= 0.2.2 (you should `pip install neural-tangents --upgrade`)

**Comment by DarrenZhang01** [comment]
It runs through this time. Thanks for solving this issue!
