### ISSUE TITLE
Some Tests Skipped

### ISSUE THREAD

**Issue by DarrenZhang01** [google/neural-tangents#38]
Hi, I am running the test files for Neural Tangents and a lot of cases were skipped. For example, 96 / 127 test cases were skipped in Neural Tangents stax test cases. I looked at the implementation of the tests and it seemed to be the invalid test cases that triggered the `SkipTest` in unit test. I am wondering if this is an expected thing. Thanks!

**Comment by romanngg** [comment]
Hi Daren, in general yes, we skip some tests on purpose if
1) the test is running on CPU, to speed up our internal / Travis CI test runs.
2) the test is parameterized, and some particular configuration is doesn't need to be run (e.g. a fully-connected network doesn't have a `padding` parameter, so we'd skip all but one configurations in the `padding` x `model type` cartesian grid)

**Comment by DarrenZhang01** [comment]
I see. Thanks for the clarification, Roman!
