### ISSUE TITLE
`_reduce_window_sum` in stax

### ISSUE THREAD

**Issue by DarrenZhang01** [google/neural-tangents#42]
Hi, could anyone explain to me the use of `_reduce_window_sum` in the core file `stax.py`? It appears twice on line 3095 and 3049 and it is an internal method for JAX lax (hard to find documentation). Thanks ahead!

[https://github.com/google/neural-tangents/blob/master/neural_tangents/stax.py#L3049](https://github.com/google/neural-tangents/blob/master/neural_tangents/stax.py#L3049)
[https://github.com/google/neural-tangents/blob/master/neural_tangents/stax.py#L3095](https://github.com/google/neural-tangents/blob/master/neural_tangents/stax.py#L3095)

**Comment by romanngg** [comment]
1) The second appearance is an accidental code duplicate - will remove the whole method, thanks!

2) The operation is essentially sum-pooling, corresponding to https://www.tensorflow.org/xla/operation_semantics#reducewindow

3) The purpose of the operation is finding out the covariance of outputs of a random-weight CNN layer given fixed inputs with covariance `mat`. The function is essentially (modulo weight and bias variances being 1 and 0 resp) the `\mathcal A` operator from Eq (5) in [\*]. This particular method is being called when only same-pixels-different-images covariances are being tracked (i.e. `\alpha = \alpha'` in Eq (5), `k.diagonal_spatial = True` in the code; see also Figure 3 in [\*]), and in this case, the output covariance can be computed via a simple pooling operation over the input covariance matrix `mat`. Alternatively, if all different-pixels-different-images covariances are tracked, a more complex operation is performed (sequence of convolutions with diagonal filters) in another function https://github.com/google/neural-tangents/blob/24549f30678fc79bbc7f0185dc4aba70fa691598/neural_tangents/stax.py#L2901 is called. See section 3 in [\*] for discussion on when and why one can get away with trackiing only same-pixels covariance entries.

[*] https://arxiv.org/abs/1810.05148

Hope this helps, lmk if you have other questions!

**Comment by DarrenZhang01** [comment]
> 1. The second appearance is an accidental code duplicate - will remove the whole method, thanks!
> 2. The operation is essentially sum-pooling, corresponding to https://www.tensorflow.org/xla/operation_semantics#reducewindow
> 3. The purpose of the operation is finding out the covariance of outputs of a random-weight CNN layer given fixed inputs with covariance `mat`. The function is essentially (modulo weight and bias variances being 1 and 0 resp) the `\mathcal A` operator from Eq (5) in [*]. This particular method is being called when only same-pixels-different-images covariances are being tracked (i.e. `\alpha = \alpha'` in Eq (5), `k.diagonal_spatial = True` in the code; see also Figure 3 in [*]), and in this case, the output covariance can be computed via a simple pooling operation over the input covariance matrix `mat`. Alternatively, if all different-pixels-different-images covariances are tracked, a more complex operation is performed (sequence of convolutions with diagonal filters) in another function https://github.com/google/neural-tangents/blob/24549f30678fc79bbc7f0185dc4aba70fa691598/neural_tangents/stax.py#L2901
>     is called. See section 3 in [*] for discussion on when and why one can get away with trackiing only same-pixels covariance entries.
> 
> [*] https://arxiv.org/abs/1810.05148
> 
> Hope this helps, lmk if you have other questions!

Thanks very much for the detailed explanation, Roman!
