### ISSUE TITLE
JAX lax `cond` in utils

### ISSUE THREAD

**Issue by DarrenZhang01** [google/neural-tangents#43]
Hi Roman @romanngg , would you mind explaining the use of `jax.lax.cond` in [https://github.com/google/neural-tangents/blob/master/neural_tangents/utils/utils.py#L359-L361](https://github.com/google/neural-tangents/blob/master/neural_tangents/utils/utils.py#L359-L361)? (My question is: one boolean is enough for `cond` but three are given?) Thanks!

**Comment by romanngg** [comment]
Good observation, apparently they changed the API recently, but still support the old `condition, true_operand, true_fn, false_operand, false_fn` API as well: https://github.com/google/jax/blob/6b471e2ac6813d894f7a97dc0c287d325b5d6760/jax/lax/lax_control_flow.py#L643.

Will update soon!

**Comment by DarrenZhang01** [comment]
> Good observation, apparently they changed the API recently, but still support the old `condition, true_operand, true_fn, false_operand, false_fn` API as well: https://github.com/google/jax/blob/6b471e2ac6813d894f7a97dc0c287d325b5d6760/jax/lax/lax_control_flow.py#L643.
> 
> Will update soon!

Thanks for letting me know, Roman! Let me know after it is updated!

**Comment by romanngg** [comment]
Fixed in https://github.com/google/neural-tangents/commit/156a4f79bc3bbd24f231ea550eddb4e1ec05eab1 !
