### ISSUE TITLE
Kernel Shape Calculation 

### ISSUE THREAD

**Issue by DarrenZhang01** [google/neural-tangents#45]
Hi Roman @romanngg , would you mind explaining a bit about the kernel shape calculation, especially the `_propagate_shape` function? I am also curious about the use of `akey`. Thanks a lot!

[https://github.com/google/neural-tangents/blob/master/neural_tangents/stax.py#L2072](https://github.com/google/neural-tangents/blob/master/neural_tangents/stax.py#L2072)

**Comment by sschoenholz** [comment]
Hi @DarrenZhang01, I'm happy to take this one. The idea here is that during computation of the kernel, we would like to know the shape of the intermediate (pre-)activations in the finite version of the computation. To do this, we use JAX's abstract evaluation machinery to infer the shapes using the `init_fn` without actually instantiating any parameters. Here `akey` is an abstract version of key that retains only shape and dtype information. If you want to know more, you might want to check out one of the JAX talks (there is a great one by Skye that's recorded somewhere) where they explain how tracing works.

**Comment by DarrenZhang01** [comment]
Thanks very much Sam @sschoenholz ! I see that `akey` is an abstract level (`ShapedArray`) of key representation. If I understand correctly, when `akey` serves as the input for `abstract_eval_fun` in `_propagate_shape`, it is only used as a `PartialVal` object in generating the `Jaxpr`?

**Comment by sschoenholz** [comment]
I think that's basically correct. As a technical point, I believe JAX doesn't instantiate the jaxpr explicitly, but evaluates the shape while tracing the jaxpr.

**Comment by DarrenZhang01** [comment]
I see. Thanks, Sam!
