### ISSUE TITLE
Insight Needed for the Shape Inference of the Key

### ISSUE THREAD

**Issue by DarrenZhang01** [google/neural-tangents#46]
Hi Roman @romanngg and Sam @sschoenholz , I am currently working on the migration/reconstruction of Neural Tangents from JAX to TensorFlow 2.x, as an R&D project for the TensorFlow team. For the shape inference based on the abstract key [https://github.com/google/neural-tangents/blob/master/neural_tangents/stax.py#L2076](https://github.com/google/neural-tangents/blob/master/neural_tangents/stax.py#L2076), we have not found an appropriate way in plugging in an equivalent TF API here. I am currently considering disabling the functionality around this line since `akey` only seems to be used in generating rng key later on? Could you provide us some insights from the Neural Tangents perspective? If I choose to disable it, what would be an appropriate range? Thanks a lot!

**Comment by sschoenholz** [comment]
Actually, the shape inference is used in a number of places. Anywhere you see `shape1` or `shape2` accessed in the `Kernel` object uses shape inference. AFAIK the main places where these shapes show up are 1) computing the NTK in the standard parameterization (see e.g. https://arxiv.org/pdf/2001.07301.pdf), 2) masking, and 3) concatenating layers along the channel dimension. I suppose if you disable these features you could set `shape1` and `shape2` to be dummy tuples and everything else should still work.

**Comment by DarrenZhang01** [comment]
I see, thanks so much, Sam! Would you mind giving an example of what you mean by "dummy tuples"?

**Comment by DarrenZhang01** [comment]
Thanks Sam, we had a meeting just now and currently have some potential solutions.
