### ISSUE TITLE
Tree Flattening in Shape Inference

### ISSUE THREAD

**Issue by DarrenZhang01** [google/neural-tangents#47]
Hi, could anyone explain to me the reason for composing `(akey,)` and `{}` as the input for the `tree_flatten` function in [https://github.com/google/neural-tangents/blob/master/neural_tangents/stax.py#L2074](https://github.com/google/neural-tangents/blob/master/neural_tangents/stax.py#L2074)? Thanks!

**Comment by romanngg** [comment]
AFAIK this was due to the specifics of the `WrappedFun` API used at that time; Sam has recently updated that section in https://github.com/google/neural-tangents/commit/01db103beb35634e90270daf420eb9a8a2cbb339 to use the public / more straigtforward JAX API `eval_shape`.

**Comment by DarrenZhang01** [comment]
Great! Thanks @romanngg @sschoenholz !
