### ISSUE TITLE
Test Cases with Input Shape `(-1, 7)`

### ISSUE THREAD

**Issue by DarrenZhang01** [google/neural-tangents#48]
Hi, could you confirm that the input is `(-1, 7)` in [https://github.com/google/neural-tangents/blob/master/tests/stax_test.py#L1017](https://github.com/google/neural-tangents/blob/master/tests/stax_test.py#L1017)? Since this is not reshaping, what does `-1` represent here as the first dimension? Thanks!

**Comment by romanngg** [comment]
I think this just means it's not being used, or used in places where the actualized size at axis 0 can be inferred from the context. E.g. by default the leading dimension is the batch dimension, that does not influence how parameters of the Dense layer are initialized. I imagine it could error if any other dimension is -1, or if `batch_axis != 0` (but it might also work, if again, the size where `-1` is used can be inferred from the context).

It may be cleaner to just pass `X0_1.shape` there though.

**Comment by DarrenZhang01** [comment]
I see, thanks!
