### ISSUE TITLE
Possible typo in README.md

### ISSUE THREAD

**Issue by NewJerseyStyle** [google/neural-tangents#49]
## In the last part of [5-minute-intro](https://github.com/google/neural-tangents#5-minute-intro)
I guess the line assigning `y_test_ntk` should pass parameter `get='ntk'` instead of `get='nngp'`

```python
y_test_ntk = predict_fn(x_test=x_test, get='nngp')
```

I think it should be:
```python
y_test_ntk = predict_fn(x_test=x_test, get='ntk')
```

**Comment by romanngg** [comment]
Thanks, fixed! https://github.com/google/neural-tangents/commit/17e7b5203149228fc6f06d1c4993112d23f40495
