### ISSUE TITLE
Shape `(-1,) + input_shape` in `kernel_fns`

### ISSUE THREAD

**Issue by DarrenZhang01** [google/neural-tangents#53]
Hi, maybe somewhat similar to https://github.com/google/neural-tangents/issues/48, but what would be a good alternative instead of passing `-1` as the first input dimension here? (TF Numpy array does not recognize negative shapes) Thanks!

https://github.com/google/neural-tangents/blob/master/tests/empirical_test.py#L85

`_, params = init_fn(key, (-1,) + input_shape)`

**Comment by romanngg** [comment]
I think any positive number should work there, as initialization of all layers in stax does not depend on the batch size (formally, it expects the input batch size, but it doesn't matter in any of the existing layers).

**Comment by DarrenZhang01** [comment]
I see. Thanks very much, Roman!
