### ISSUE TITLE
Question about `test_composition_conv` in Stax Tests

### ISSUE THREAD

**Issue by DarrenZhang01** [google/neural-tangents#54]
Hi, sorry for bothering. In the `test_composition_conv_avg_pool` test cases, some outer products on the covariance matrices are performed while doing Kernel transformation. In the outer product function, there is the `interleave_ones` operation which adds ones to the covariance dimensions:
```
def outer_prod(x, y, start_axis, end_axis, prod_op):
  if y is None:
    y = x
  x = interleave_ones(x, start_axis, end_axis, True)
  y = interleave_ones(y, start_axis, end_axis, False)
  tf.print("x: {}, y: {}".format(x.shape, y.shape), output_stream=sys.stdout)
  return prod_op(x, y)
```
When I print out the shapes after `interleave_ones`, some shapes are like `x: (5, 1, 8, 1, 8, 1), y: (1, 5, 1, 8, 1, 8)` which obviously do not match. In this case, would you mind explaining the role of `interleave_ones` and how could the unmatched shapes be multiplied together? Thanks!

**Comment by sschoenholz** [comment]
Hey Darren, the purpose here is to use numpy's broadcasting semantics to compute the outer product. Here I'm defining an outer product for two tensors X of shape (n1, n2, n3) and Y of shape (n4, n5, n6) to be XY of shape (n1, n4, n2, n5, n3, n6). Of course, there is ambiguity in how one defines the outer product in terms of where the various dimensions should go but this is one such choice.

**Comment by DarrenZhang01** [comment]
This is pretty cool, Sam! So you are regarding each dimension as a single vector and doing outer product for the according dimensions of `x` and `y`. In order to perform the outer product, you turned each single vector/dimension into a 2D matrix. Thanks for the explanation!

**Comment by DarrenZhang01** [comment]
Hi Sam @sschoenholz , a followup question: when calling `_get_diagonal_outer_prods`, the python built-in operator `op.mul` is sent in as the API for the above broadcasting? 

https://github.com/google/neural-tangents/blob/master/neural_tangents/stax.py#L2153

Thanks!

**Comment by romanngg** [comment]
I'm not sure I fully understand your question, but `op.mul` is the binary combinator function to produce results, i.e. you have `outer_product(operation, x, y)[i1, j1, i2, j2, ..., ik, jk] = operation(x[i1, i2, ..., ik], y[j1, j2, ..., jk])`, and `operation` in our code can be both multiplication and addition in some other places. Let me know if this helps or not!

**Comment by DarrenZhang01** [comment]
Hi Roman @romanngg , sorry for the confusion. My question is: as Sam mentioned, Numpy or JAX Numpy broadcasting should be used in doing the irregular matrix multiplication/outer product. But instead, only `op.mul`, which is a python built-in is used? Thanks a lot!

**Comment by romanngg** [comment]
IIUC, `op.mul` is the binary operation used to compute the entries in the resulting matrix, but it has no influence on the matrix shape or broadcasting rules - numpy broadcasting rules are being used to compute the resulting shape and how the input/output indices are related. That's why we have it as an argument - so that we could get an "outer sum" just like the "outer product" and any "outer <binary operation>". See also https://en.wikipedia.org/wiki/Outer_product#In_programming_languages, in wiki notation `f` is our `operation`. Lmk if this helps!

**Comment by DarrenZhang01** [comment]
I think I got it this time. In order to apply the broadcasting rules or calculating the output shapes, no Numpy operations like `outer` needs to be directly involved, and just two input Numpy arrays `cov1` and `cov2` plus a binary operation are enough. Something very similar to `np.array([1, 2, 3]) + 10`. Sorry for the misunderstanding and thanks for the explanation, Roman! @romanngg
