### ISSUE TITLE
Difference between the General `Kernel` and `AnalyticKernel`

### ISSUE THREAD

**Issue by DarrenZhang01** [google/neural-tangents#57]
Hi, would you mind explaining the difference between a general `Kernel` type and a `<class 'neural_tangents.utils.utils.AnalyticKernel'>` type? Thanks ahead!

**Comment by romanngg** [comment]
I might miss some nuance here, but AFAIK

1) `Kernel` is the (static) dataclass always containing _all_ kernel metadata used to compute the (analytic) kernel of a deep network. Most of the `stax.py` code works with `Kernel` objects, and a typical `kernel_fn` has a `Kernel -> Kernel` signature.
https://github.com/google/neural-tangents/blob/83fece767bccfe4e11872e8fc7128bb4d9325fa8/neural_tangents/utils/kernel.py#L27

2) `AnalyticKernel` is the user-facing, dynamically defined `namedtuple` class that contains a _subset_ of the `Kernel` metadata, based on what the user passes as `get` when calling `kernel_fn`. This is used to support quick attribute / tuple unpacking (as described in code block 3 in https://github.com/google/neural-tangents#5-minute-intro) as opposed to always having to access them as attributes of the full `Kernel` object.

https://github.com/google/neural-tangents/blob/83fece767bccfe4e11872e8fc7128bb4d9325fa8/neural_tangents/utils/utils.py#L60

**Comment by DarrenZhang01** [comment]
Thanks for the explanation, Roman! Then is there any existing function to convert between the two or it is necessary to manually retrieve the attributes and their values?

**Comment by romanngg** [comment]
Will close this as answered, don't hesitate to reopen if you have other questions!
