### ISSUE TITLE
module 'jax.core' has no attribute 'eval_context'

### ISSUE THREAD

**Issue by xiaulinhu** [google/neural-tangents#66]
when I use jax 0.1.75 run the following code, I get errors
![image](https://user-images.githubusercontent.com/56224052/92433682-5765c380-f1d0-11ea-9d81-d5157dcc55da.png)

**Comment by romanngg** [comment]
Please see https://github.com/google/neural-tangents/issues/64#issuecomment-687860851 - JAX pypi is a bit out of date; will update the docs soon!

**Comment by xiaulinhu** [comment]
Thank you!
