### ISSUE TITLE
Function space linearization encounters AttributeError: module 'jax.core' has no attribute 'eval_context'

### ISSUE THREAD

**Issue by lionelmessi6410** [google/neural-tangents#69]
Hello,

I was playing with sample code provided by 5-Minute Intro and Colab. However, when I tried to implement the function space linearization, **AttributeError: module 'jax.core' has no attribute 'eval_context'** occurs when calling ```predictor``` returned by ```nt.predict.gradient_descent_mse```. 

I did trace the source code and notice that in the ```predict.py```, you wrote ```with jax.core.eval_context():```, which caused the corresponding **AttributeError**, and I am not sure why this happens. Is this the problem relevant to Jax version? After removing ```with jax.core.eval_context():```, the results were identical to [Function Space Linearization.ipynb](https://colab.research.google.com/github/google/neural-tangents/blob/master/notebooks/function_space_linearization.ipynb).

**Comment by romanngg** [comment]
That feature was introduce in JAX recently, could you try to upgrade JAX to >=0.1.77? Pushed https://github.com/google/neural-tangents/commit/0aaaf06f7fd96a2281aadd088f32ad0e01625669 to make sure we require the latest version, sorry for the confusion!

**Comment by lionelmessi6410** [comment]
> That feature was introduce in JAX recently, could you try to upgrade JAX to >=0.1.77? Pushed [0aaaf06](https://github.com/google/neural-tangents/commit/0aaaf06f7fd96a2281aadd088f32ad0e01625669) to make sure we require the latest version, sorry for the confusion!

Thanks for your quick reply. There is no more **AttributeError** after upgrading!
