### ISSUE TITLE
confused by the shape of analytic NTK when evaluated at data points

### ISSUE THREAD

**Issue by liutianlin0121** [google/neural-tangents#7]
Hi, 

It seems to me that when evaluated at input data, the analytic NTK dimensions are not consistent with empirical NTK dimensions. Concretely, consider a small MLP as the follows:

```python
from neural_tangents import stax

init_fun, apply_fun, ker_fun = stax.serial(
    stax.Dense(5), stax.Relu(),
    stax.Dense(2))
```

Also, consider a set of 10 input data points, each of dimension 100.

```python
nr_samples = 10
input_data_dim = 100 

from jax import random
# some data points which will be fed into the neural net.
x1 = random.normal(random.PRNGKey(1), (nr_samples, input_data_dim)) 
```
We can evaluate the empirical NTK with some random parameters `rand_params`

```python
from neural_tangents.api import get_ker_fun_empirical

# the empirical kernel function
from neural_tangents.api import get_ker_fun_empirical
empirical_ker_fun = get_ker_fun_empirical(apply_fun) 

# some random parameters
_, rand_params = init_fun(random.PRNGKey(1), (-1, 100))  

# empirical NTK matrix evaluated on data points x1
emp_kernel_mat_x1 = empirical_ker_fun(x1, x1, rand_params).ntk 
print(emp_kernel_mat_x1.shape) #  gives (10, 10, 2, 2)
```

With `emp_kernel_mat_x1.shape`, we see that the shape of `emp_kernel_mat_x1` is (10, 10, 2, 2), which is as expected -- the shape depends on both output dimension 2 and sample size 10. However, when evaluating the **analytic kernel** on the same data points, the shape differ.

```python
analytic_kernel_mat_x1 = ker_fun(x1, x1)

print(analytic_kernel_mat_x1.ntk.shape) # gives (10, 10)
```

Here `print(analytic_kernel_mat_x1.ntk.shape)` gives (10, 10), which is different from the shape of empirical one (10, 10, 2, 2). 

I am wondering why the analytic kernel here seems to ignore the neural network output dimension (2, in this case). Would it be possible to get an analytic kernel matrix of the format (#sample, #sample, output_dim, output_dim), which is the same format as the empirical one? Many thanks!!

Best,
Tianlin

**Comment by sschoenholz** [comment]
Hi Tianlin,

Thanks for the question! The reason for the shape mismatch is following a `Dense` layer, the infinite width kernel with be block-diagonal in the outputs so that `analytic_kernel_mat_x1[..., 1, 0] == analytic_kernel_mat_x1[..., 0, 1] == 0` and `analytic_kernel_mat_x1[..., 0, 0] == analytic_kernel_mat_x1[..., 1, 1]`. To save memory, we therefore do not instantiate the extra dimensions where the structure is trivial. However, all of our prediction functions are designed to operate on arrays of either shape.

If being able to instantiate arrays with the true output shape would be useful for you, we can certainly think about adding something to that effect. Can you give us an example use case?

Best,
Sam

**Comment by liutianlin0121** [comment]
Many thanks for your answer! 

One use case is to visualize the the convergence speed of empirical NTK as the neural network width grows.  Let's say we have a one-hidden-layer MLP whose hidden layer width is <a href="https://www.codecogs.com/eqnedit.php?latex=l" target="_blank"><img src="https://latex.codecogs.com/gif.latex?l" title="l" /></a>. Also, we have a collection of data points <a href="https://www.codecogs.com/eqnedit.php?latex=\mathcal{X}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\mathcal{X}" title="\mathcal{X}" /></a>. To study the asymptotic convergence of the empirical NTK, it would be nice if it is possible to evaluate and visualize the squared distance between the empirical NTK and analytic NTK, 

<a href="https://www.codecogs.com/eqnedit.php?latex=\|&space;\mathcal{K}_{\textnormal{empirical}}^l(\mathcal{X},&space;\mathcal{X})&space;-&space;\mathcal{K}_{\textnormal{analytic}}(\mathcal{X},&space;\mathcal{X})\|_{{F}}^2" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\|&space;\mathcal{K}_{\textnormal{empirical}}^l(\mathcal{X},&space;\mathcal{X})&space;-&space;\mathcal{K}_{\textnormal{analytic}}(\mathcal{X},&space;\mathcal{X})\|_{{F}}^2" title="\| \mathcal{K}_{\textnormal{empirical}}^l(\mathcal{X}, \mathcal{X}) - \mathcal{K}_{\textnormal{analytic}}(\mathcal{X}, \mathcal{X})\|_{{F}}^2" /></a>

as the hidden layer width <a href="https://www.codecogs.com/eqnedit.php?latex=l" target="_blank"><img src="https://latex.codecogs.com/gif.latex?l" title="l" /></a> goes to infinity.

**Comment by romanngg** [comment]
An updates on this: after a76bbb494f19af4f8c9c1a1b0904e91b105f769e you can flexibly specify so-called `trace` and `diagonal` axes when computing the empirical kernel, which corresponds to the axes along which you want to compute only the trace or the diagonal respectively. This allows you to obtain the empirical kernel that will match the shape of the analytic kernel, and also will converge faster (than the full 10x10x2x2) to the true kernel (even if you were to mask out entries in the full 10x10x2x2 kernel that you know would converge to 0):
https://colab.research.google.com/gist/romanngg/6353e6dc25b34556e705a334c29801c4/trace_axes_for_faster_convergence.ipynb

Also the new docs about these parameters https://neural-tangents.readthedocs.io/en/latest/neural_tangents.empirical.html explain the shapes a bit better, so I hope it helps!

(We still don't provide the method to upscale the kernel with `trace_axes != ()` to the full shape 10x10x2x2 shape, but this should be reasonably easy to do on the spot, see e.g. the colab link)
