### ISSUE TITLE
when the dimension of ntk_train_train exceed 32767, gradient_descent_mse returns error result.

### ISSUE THREAD

**Issue by taozhe1036** [google/neural-tangents#70]
Hi all,
I want to test the gradient_descent_mse on the whole mnist dataset. 
The whole ntk_train_train is  60000X60000.
When I use jax.numpy, the linalg.eigh in the inner function _get_fns_in_eigenbasis of gradient_descent_mse returns a memory error.　
My platform is ubuntu 16.04 LTS, which has four RTX2080 GPU and 62GB memory.
Then I try to solve this problem with numpy to calculate the eigenvalue and eigenvector with 
62GB memory to avoid memory error without using GPU.
Unfortunately, numpy.linalg.eigh on ntk_train_train with dimension 60000X60000 returns all zero eigenvalues and eigenvectors.  This problem is with numpy.linalg(https://github.com/numpy/numpy/issues/13956).
Also I tried scipy.linalg.eigh, but I took a day without any result. It is so slow and I tried a suggestion in https://github.com/scipy/scipy/issues/9212. But it returns ValueError: illegal value in argument 11 of internal sygvd.

Scipy/Numpy/Python version information:
1.3.0 1.16.4 3.7.3

Thank you very much for your efforts in advance!

Best regards

**Comment by romanngg** [comment]
Not sure about the numpy/scipy issues, but you could try running your JAX/XLA code on CPU as well (there is a chance it will hit the same issues, but perhaps it's executed differently), e.g. by either
```
import jax
jax.config.update('jax_platform_name', 'cpu')
```
at the beginning of your code, or sticking all your inputs to NT functions on CPU via
```
jax.device_put(ntk_train_train, jax.devices('cpu')[0])
```
(in this case, computations should be carried out on the same device as the inputs, i.e. on CPU; if arrays are not sticked like this, they would be put on the default device as soon as possible, and that is the GPU). You can check where a JAX array is by calling `ntk_train_train.device_buffer.platform()`

**Comment by taozhe1036** [comment]
> Not sure about the numpy/scipy issues, but you could try running your JAX/XLA code on CPU as well (there is a chance it will hit the same issues, but perhaps it's executed differently), e.g. by either
> 
> ```
> import jax
> jax.config.update('jax_platform_name', 'cpu')
> ```
> 
> at the beginning of your code, or sticking all your inputs to NT functions on CPU via
> 
> ```
> jax.device_put(ntk_train_train, jax.devices('cpu')[0])
> ```
> 
> (in this case, computations should be carried out on the same device as the inputs, i.e. on CPU; if arrays are not sticked like this, they would be put on the default device as soon as possible, and that is the GPU). You can check where a JAX array is by calling `ntk_train_train.device_buffer.platform()`

Thanks for your helpful suggestion. I test JAX on CPU for large matrix eigen. My code is 

import jax.numpy as np
import jax.scipy as spy
import jax

jax.config.update('jax_platform_name', 'cpu')
n=32767
array = np.diag(numpy.random.random(n,))

values, funcs =np.linalg.eigh(array)
values, funcs = spy.linalg.eigh(array)

I test both linalg.eigh of  jax.numpy and jax.scipy, they all return 

F external/org_tensorflow/tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Invalid argument: shape's dimensions must not be < 0; dimension at index 0 was -1094727295
Aborted (core dumped)

**Comment by romanngg** [comment]
Thanks for checking and filing https://github.com/google/jax/issues/4358 - it does look like a JAX/XLA bug. I've had similar issues from time to time with XLA/TF, but thought it was fixed by today, apparently not.
