### ISSUE TITLE
gradient of kernel_fn with autograd

### ISSUE THREAD

**Issue by emited** [google/neural-tangents#73]
Hi, 

Really neat lib! I was wondering if it is possible to compute the gradient of the kernel with respect to the input data using autograd? I have had several unsuccessful attempts and was wondering if it were even possible!

Thanks,

**Comment by sschoenholz** [comment]
Thanks for trying out NT! It should definitely be possible to compute gradients through autograd. Can you share some code showing what you're trying to do and we can help debug?

Best,
Sam

**Comment by emited** [comment]
Thanks a lot for your response! I was obtaining NaNs when computing the gradients when I had ReLU activations. I have found how to solve the problem, with the help of this issue: https://github.com/google/neural-tangents/issues/76#issuecomment-707159772.

Closing this issue.

**Comment by ed1d1a8d** [comment]
@emited Just want to say you can actually take gradients of the kernel with ReLU activations. You just need to set the option `do_backprop` when you construct the network:
https://github.com/google/neural-tangents/blob/c654ac05d3a6f9909cfbd048ed95b1f537b7ff6a/neural_tangents/stax.py#L2953-L2965

**Comment by romanngg** [comment]
FYI, in the latest release https://github.com/google/neural-tangents/releases/tag/v0.3.6 we have improved numerical stability of differentiating nonlinearities, and got rid of the `do_backprop` parameter altogether! If you encounter any issues, please lmk.
