### ISSUE TITLE
 Is there any way to use ``neural_tangents.predict`` library with ``stax.Aggregate`` function?

### ISSUE THREAD

**Issue by jl626** [google/neural-tangents#79]
First, thank you for this handy library. 
I have a question about ``stax.Aggregate`` function.
I tried to use ``neural_tangents.predict`` library with graph neural tangent kernel (i.e.``stax.aggregate`` function) 

For example, 
```python
# graph NTK
layer = []
for _ in range(3):
    layer += [stax.Dense(), stax.Relu(), stax.Aggregate(aggregate_axis=1,batch_axis=0,channel_axis=2)]
_, _, kernel_fn = stax.serial(*(layers + [stax.GlobalAvgPool()]))


# neural-tangents predict library 
predict_fn = nt.predict.gradient_descent_mse_ensemble(kernel_fn, x_train,y_train, diag_reg=1e-6, pattern=(p1,p1))

# inference
fx_test_nngp, fx_test_ntk = predict_fn(x_test=x_test) # raise error and  predict_fn(x_test=x_test, pattern=(p2,p1)) not accepted
fx_test_nngp.block_until_ready()
fx_test_ntk.block_until_ready()
```
It seems ``predict_fn`` does not accept the variable ``pattern``. I wonder is there a specific way to use ``neural_tangents.predict`` library with graph neural tangent kernel? 

Thanks again!

**Comment by SiuMath** [comment]
Thanks for bringing up this issue. We should definitely fix it. 

A quick solution is to marginalize `pattern` in `kernel_fn` by setting

`kernel_fn = functools.partial(kernel_fn, pattern=(p1, p1))`

Let me know if it solves the problem.

**Comment by romanngg** [comment]
IIUC the issue here is in this line:
```
fx_test_nngp, fx_test_ntk = predict_fn(x_test=x_test) # raise error and  predict_fn(x_test=x_test, pattern=(p2,p1)) not accepted
```
which doesn't accept a `kernel_fn`, so we can't pass `p2`. We should definitely fix it.

For now you could also use the `nt.predict.gradient_descent_mse` which accepts kernels rather than kernel function (see https://github.com/google/neural-tangents/issues/72) for discussion on how they are (not very) different. It doesn't compute the covariance though.

**Comment by jl626** [comment]
Many thanks for prompt reply. You are right, the problem is that I cannot pass the variable `p2` to `predict_fn`.
I appreciate your suggestion, in a mean time, I will use ``nt.predict.gradient_descent_mse``. If I understand correctly, ``nt.predict.gradient_descent_mse`` with sufficiently large parameter ``t`` is equivalent of solving the kernel regression in following form .

```python
kernel_test_train.dot(scipy.linalg.solve(kernel_train_train + diag_reg*np.eye(n_train,), y_train))
```

Is that right? I will read more details in #72. Really appreciate your fast reply and suggestions!

**Comment by romanngg** [comment]
Correct! In your case above, you could write something like:
```python
k_train_train = kernel_fn(x_train)
k_test_train = kernel_fn(x_test, x_train)

predict_fn_ntk = nt.predict.gradient_descent_mse(k_train_train.ntk, y_train)
predict_fn_nngp = nt.predict.gradient_descent_mse(k_train_train.nngp, y_train)

# inference
fx_test_ntk = predict_fn_ntk(t=None, k_test_train=k_test_train.ntk, fx_test_0=0., fx_train_0=None)
fx_test_nngp = predict_fn_nngp(t=None, k_test_train=k_test_train.nngp, fx_test_0=0., fx_train_0=None)
```

Note that passing `t=None` means analytic infinite time, and will evaluate essentially the expression that you have above (while passing `t=np.inf` should give you the same results, but go through eigendecomposition, and is probably suboptimal in terms of time and numerical accuracy, but you can use it as a sanity check)

One final detail is watch out for this parameter https://github.com/google/neural-tangents/blob/37494ec4859178231974ca996f736245c092c2a5/neural_tangents/predict.py#L53 to make sure you regularize in absolute units as above, you need to set `diag_reg_absolute_scale=True`

**Comment by romanngg** [comment]
Added a somewhat hacky fix for it - now `nt.predict_gradient_descent_mse_ensemble` accepts `**kernel_fn_train_train_kwargs` (i.e. `pattern=(pattern_train, pattern_train)`), while the `predict_fn` call accepts `**kernel_fn_test_test_kwargs` (i.e. `pattern=(pattern_test, pattern_test)`; see docs https://neural-tangents.readthedocs.io/en/latest/neural_tangents.predict.html#neural_tangents.predict.gradient_descent_mse_ensemble).

(`**kernel_fn_test_train_kwargs` are constructed under the hood by picking values from each)

Also, for a somewhat cleaner API, if you only want infinite-time predictions, you may use `nt.predict.gp_inference`, where, as in the example above, you can first precompute the kernel matrices.

**Comment by NaCL16** [comment]
Hello, Romanngg, I have recently found that if I consider the diag_reg_absolute_scale = true, which means that  k_train_train + diag_reg * I will replace the original k_train_train. However, the analytic results under this situation can not agree to the results generated by GP.inference
