### ISSUE TITLE
Option `do_stabilize=True` leads to TypeError in kernel execution

### ISSUE THREAD

**Issue by White-Link** [google/neural-tangents#82]
Hi, thanks a lot for this nice library!

I noticed that enabling the option `do_stabilize` in `ABRelu` leads to the error `TypeError: max requires ndarray or scalar arguments, got <class 'list'> at position 0.` at line 2903 of file `stax.py`:
```python
factor = np.max([np.max(np.abs(nngp)), 1e-12])
```

Here is a MWE:
```python
import neural_tangents as nt
import numpy as np

init_fn, apply_fn, kernel_fn = nt.stax.serial(
    nt.stax.Dense(512), nt.stax.ABRelu(0, 1, do_stabilize=True),
    nt.stax.Dense(1)
)

a = np.zeros((10, 10))
print(kernel_fn(a, a))
```

**Comment by romanngg** [comment]
Thanks for pointing this out, fixed!
