### ISSUE TITLE
Question about the dimension of NTK

### ISSUE THREAD

**Issue by chenwydj** [google/neural-tangents#83]
In `Disentangling_Trainability_and_Generalization.ipynb`

```python
def mean_predictor(ntk_fn, x_train, y_train, x_test, reg=0.):
  ktd = ntk_fn(x_test, x_train)
  kdd = ntk_fn(x_train, x_train)
  @vmap
  def inv(k):
    return np.linalg.inv(k + reg * np.eye(k.shape[0]))
  return np.einsum('ijk,ikl,lm->ijm', ktd, inv(kdd), y_train)
```

Why does the NTK (`ktd` and `ktd`) have three dimensions? As I understand, for MSE loss, the shape of NTK is N1xN2, right? (N1, N2 are the number of training or testing data)

Thank you!

**Comment by SiuMath** [comment]
That is a good question.

The vanilla ktd is 2d.

Here we have a *sequence* of ntks corresponding to different layers.  See
“def ntk(...)”

Best
Lechao

**Comment by chenwydj** [comment]
I see. Thank you very much!

Best,
Wuyang
