### ISSUE TITLE
Using gp_inference to predict the posterior distribution - What is nngp_test_test?

### ISSUE THREAD

**Issue by samuelkim314** [google/neural-tangents#92]
I want to use neural_tangents.predict.gp_inference to predict a distribution (mean and variance) on a test set. The documentation says that it returns a function `predict_fn(get, k_test_train, nngp_test_test)` and the docstring for the code says that `nngp_test_test` is a "A test-test NNGP array," but I see no mention of this NNGP array anywhere else in the documentation. How do I produce this?

**Comment by ryanwolcott321** [comment]
(get, k_test_train, nngp_test_test)

**Comment by ryanwolcott321** [comment]
https://graph.instagram.com/v9.0/17841405822304914/insights?metric=impressions,reach,profile_views&period=day&access_token=IGQVJ

**Comment by romanngg** [comment]
Assuming that you've computed `k_train_train` and `k_test_train` with a `kernel_fn`, then `nngp_test_test = kernel_fn(x_test, None, 'nngp')`. You can find an example in the unit tests:
https://github.com/google/neural-tangents/blob/b1e750cb86f98e73cfe426494e8c647a271df928/tests/predict_test.py#L765

This variable is the covariance between the test set outputs of the infinite-width version of your network. In https://arxiv.org/pdf/1902.06720.pdf, it's `K(x, x)` and `K_(X^T, X^T)` in equations 13 and 15/16 respectively (nota that this is the same prior NNGP covariance matrix, regardless of whether you want to compute the NTK or NNGP posterior covariance).

Lmk if this helps!

**Comment by samuelkim314** [comment]
Thank you! So an example might look something like this?

```
import neural_tangents as nt
from neural_tangents import stax
import numpy as np

# Random data
x_train = np.random.rand(20, 5)
y_train = np.random.rand(20, 1)
x_test = np.random.rand(10, 5)

init_fn, apply_fn, kernel_fn = stax.serial(
    stax.Dense(512), stax.Relu(),
    stax.Dense(512), stax.Relu(),
    stax.Dense(1)
)

kernel_str = 'nngp'
k_train_train = kernel_fn(x_train, x_train, kernel_str)
predict_fn = nt.predict.gp_inference(k_train_train, y_train)
k_test_train = kernel_fn(x_test, x_train)
nngp_test_test = kernel_fn(x_test, None, 'nngp')
mean, covariance = predict_fn(kernel_str, k_test_train, nngp_test_test)
```

**Comment by romanngg** [comment]
Almost correct, with two technical comments:
1) For NNGP posterior mean/covariance, you only need NNGP prior covariances, no NTK (see eq 13 above), so for best compute efficiency you may want to pass
```diff
- k_test_train = kernel_fn(x_test, x_train)
+ k_test_train = kernel_fn(x_test, x_train, 'nngp')
```
Without specifying the `get=nngp` argument, `kernel_fn` computes NTK as well, which is not needed here.

2) For NTK, contrarily, you need prior train-train and test-train NTK _and_ NNGP covariances (but only test-test NNGP, see eq. 14-16 above), so you'd want to compute both and 
```diff
import neural_tangents as nt
from neural_tangents import stax
import numpy as np

# Random data
x_train = np.random.rand(20, 5)
y_train = np.random.rand(20, 1)
x_test = np.random.rand(10, 5)

init_fn, apply_fn, kernel_fn = stax.serial(
    stax.Dense(512), stax.Relu(),
    stax.Dense(512), stax.Relu(),
    stax.Dense(1)
)

-kernel_str = 'nngp'
+kernel_str = 'ntk'
-k_train_train = kernel_fn(x_train, x_train, kernel_str)
+k_train_train = kernel_fn(x_train, x_train)
predict_fn = nt.predict.gp_inference(k_train_train, y_train)
k_test_train = kernel_fn(x_test, x_train)
nngp_test_test = kernel_fn(x_test, None, 'nngp')
mean, covariance = predict_fn(kernel_str, k_test_train, nngp_test_test)
```
Here using the default `get=None` value makes `k_train_train` and `k_test_train` contain both NTK and NNGP matrices.

**Comment by samuelkim314** [comment]
Got it, thank you!

**Comment by samuelkim314** [comment]
Just want to point out that nngp_test_test has been removed in the newest version (0.3.6) so this no longer works.

**Comment by romanngg** [comment]
Oops, sorry for the breaking change! The variable is now called `k_test_test` (other than the new name should work as usual - if not, please lmk)
